---
- name: 0) lamp 그룹 서버 복원 작업
  hosts: lamp
  gather_facts: true
  vars:
    svcs_fw:
      - http
      - https
  tasks:
    - name: 1) 방화벽 포트 제거
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: disabled
      loop: "{{ svcs_fw }}"

    - name: 2) 서비스 내리기
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - "{{ ansible_local.custom.services.svc_db }}"
        - "{{ ansible_local.custom.services.svc_web }}"

    - name: 2) 웹 서버 설정 삭제 - index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: 3) 패키지 삭제(web/db)
      ansible.builtin.dnf:
        name:
          - "{{ ansible_local.custom.packages.pkg_db }}"
          - "{{ ansible_local.custom.packages.pkg_web }}"
        state: absent
