---
- name: 0) 팩트 배포
  hosts: web1
  gather_facts: false
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: files/custom.fact
  tasks:
    - name: 1) 원격 디렉토리 생성 - {{ remote_dir }}
      ansible.builtin.file:
        path: "{{ remote_dir }}"
        state: directory
        mode: '0755'

    - name: 2) 팩트 배포
      ansible.builtin.copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
        mode: '0644'
