---
- name: 0) 사용자 생성 + 공개 키 인증
  hosts: all
  gather_facts: false
  vars:
    pw: soldesk1.
  tasks:
    - name: 1) 사용자 생성과 암호 설정
      ansible.builtin.user:
        name: user100
        password: "{{ pw | password_hash('sha512') }}"

    - name: 2) /etc/sudoers.d/user100 파일 생성
      ansible.builtin.copy:
        src: files/user100
        dest: /etc/sudoers.d/user100
        owner: root
        group: root
        mode: '0440'

    - name: 3) 사용자 공개 키 공유
      ansible.posix.authorized_key:
        user: user100
        state: present
        key: "{{ item }}"
      with_file:
        - ~/.ssh/id_rsa.pub
