---
- name: 0) secure 로그 수집
  hosts: all
  tasks:
    - name: 1) 로그 파일 수집 - /var/log/secure
      ansible.builtin.fetch:
        src: /var/log/secure
        dest: "secure-backups/{{ inventory_hostname }}-secure"
        flat: true
