---
- name: 0) DB 서버 설치 및 기동
  hosts: database_prod
  vars:
    pkg:
      - mariadb-server
      - python3-PyMySQL
  tasks:
    - name: DB 패키지 설치 - mariadb-server, python3-PyMySQL
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ pkg }}"
      when: ansible_distribution == 'CentOS'

    - name: DB 서비스 기동
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true
