---
- name: 타임존 설정
  hosts: all
  vars:
    host_timezone: Asia/Seoul
  roles:
    - rhel-system-roles.timesync

  post_tasks:
    - name: 타임존 설정
      community.general.timezone:
        name: "{{ host_timezone }}"
      notify: chronyd 재시작

  handlers:
    - name: chronyd 재시작
      ansible.builtin.service:
        name: chronyd
        state: restarted
